# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20171004_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
