# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_cartp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=400068),
            preserve_default=False,
        ),
    ]
