# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_address_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
