# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_remove_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
